# See full configuration at https://github.com/bestit/flagception-bundle
flagception:
    features:
        get_similar:
            default: false
            constraint: 'siteKey == "ghdi" and (hostname == "localhost" or hostname matches "/germanhistorydocs/")'
        search_partner:
            default: false
            constraint: 'siteKey == "ghdi" and (hostname == "localhost" or hostname matches "/germanhistorydocs/")'
